apiVersion: apps/v1
kind: Deployment
metadata:
  name: expenses-service
  labels:
    app: expenses-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expenses-service
  template:
    metadata:
      labels:
        app: expenses-service
    spec:
      containers:
        - name: expenses-service
          image: expense-ms-expenses:latest
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: NODE_ENV
              value: production
            - name: CORS_ORIGIN
              value: http://frontend-service
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: expense-ms-secrets
                  key: mongodb_uri
