apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - expenses-deployment.yaml
  - expenses-service.yaml
  - analytics-deployment.yaml
  - analytics-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
