apiVersion: apps/v1
kind: Deployment
metadata:
  name: expenses-service
  namespace: expense-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expenses-service
  template:
    metadata:
      labels:
        app: expenses-service
    spec:
      containers:
        - name: expenses-service
          image: docker.io/1ghofrane1/expense-ms-expenses-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: NODE_ENV
              value: "production"
            - name: CORS_ORIGIN
              value: "http://localhost:5175"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: expense-ms-secrets
                  key: MONGODB_URI
